### ISSUE TITLE
tun kernel module

### ISSUE THREAD

**Issue by blankagy** [cubieplayer/Cubian#22] opened 2013-06-30 16:21 UTC
Hello, please add (or tell me what to do) the tun kernel module to the image, because i can't use the sixxs ipv6 tunnel or openvpn service.
Otherwise, this is a nice work, thank you!

**Comment by guruz** [comment] 2013-07-08 16:51
Yes, tun/tap would be awesome.

**Comment by cubieplayer** [comment] 2013-07-08 19:32
The kernel source is available [Here](https://github.com/cubieplayer/Cubian/wiki)
The kernel config is [Here](https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun4i)

**Comment by phpmysqlfreak** [comment] 2013-08-15 13:57
Is there any HowTo to follow? At my last try, I had to grab all needed packages manually - after it was finally done and the image was moved to flash, my board wasn't booting no more. - stopped working at [0.175] flash init start....

edit: finally got the solution, nothing to do with the built kernel, but the way i applied it. - that bug is listed here:
https://github.com/cubieplayer/Cubian/issues/48 - and parts of my answer here ( 
https://github.com/cubieplayer/Cubian/issues/47 ) are the way to apply such changes.

**Comment by gklipel** [comment] 2013-08-28 19:22
Hi all!!!

I was facing the same problem as blankagy and then I've got it working. How can I post the defconfig with complete NF, XT, IP, IP6 support here? The entire file wouldn't be nice, I have registered here only to post the defconfig in this post, can I attach a file at a post?

**Comment by FedericoCeratto** [comment] 2013-11-02 15:10
This seems to be a duplicate of #81

**Comment by cubieplayer** [comment] 2013-11-04 02:33
Closed duplicate with https://github.com/cubieplayer/Cubian/issues/81

**Closed as completed by cubieplayer** 2013-11-04 02:33 UTC
