### ISSUE TITLE
How to update NAND (+packages) from r4 to r5

### ISSUE THREAD

**Issue by micromys** [cubieplayer/Cubian#91] opened 2013-09-06 03:58 UTC
I've installed r4 on A10 with packages (Apache, PHP, MySQL, etc) and installed it in NAND using the nandinstaller.

How can i update nand to r5 without installing everything again? 

I ran apt-get update && apt-get upgrade and than cubian-update (from NAND). cubian-update ended with a warning (bootloader not loaded). Subsequently the A10 could not be rebooted.

**Comment by cubieplayer** [comment] 2013-09-06 04:11
Thanks for reporting.  
The warning message 'bootloader is not updated' is normal on a10, because it doesn't need to be updated. It can be fixed re-run the nand install script, but comment out the code on coping rootfs.  
It's abnormal if cubian-update breaks the bootloader. I will reproduce and fix this issue later.  
Compares to r4, r5 contains some patchs on rootfs, There is no such tool to update from r4 to r5.May be i needs to invent one.You have to re-install cubian currently.

**Comment by cubieplayer** [comment] 2013-11-08 14:34
Sry, I think it's not necessary to support this feature. I will close the issue.

**Closed as completed by cubieplayer** 2013-11-08 14:34 UTC
