### ISSUE TITLE
[cubian-packages] udevil 0.4.1-2 installscripts broken?

### ISSUE THREAD

**Issue by fieldOfView** [cubieplayer/Cubian#248] opened 2014-02-24 10:45 UTC
The 0.4.1-2 dpkg install and remove scripts have an unlisted dependency on systemctl. After apt-get upgrading from the previous version, the user is stuck with a recurring apt-get error because dpkg cannot succesfully complete the install (or the uninstall).

```
Setting up udevil (0.4.1-2) ...
dpkg: error processing udevil (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 udevil
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Sorry if this is the wrong place to report this; the cubian-packages repo does not have an issue-tracker (or does it?).

**Comment by michalliu** [comment] 2014-02-24 13:21
Thansk for report, I will check the problem.

**Comment by michalliu** [comment] 2014-02-24 13:27
The problem is caused by https://github.com/mmplayer/cubian-packages/commit/dbdb5e6de653b4fdded41f8ede5a3d2905bd1b8d#diff-a6d5f39ddd53c674d100aa20e7912a6d

systemctl is not a dependency, the script will check if systemctl is present in the system. If it does we will try to enable the devmon service.

**Comment by fieldOfView** [comment] 2014-02-24 13:56
I probably don't have my terminology correct. I agree that it is not so much a dependency, but the install/uninstall scripts seemed to depend on systemctl which is not installed on my cubian.

Anyway, the updated package does not install (or uninstall) cleanly for me. Does it for you?

**Comment by michalliu** [comment] 2014-02-24 14:48
I have systemctl installed,  it's come from the package systemd. I will try to remove systemd then see what happens.

**Comment by cubieplayer** [comment] 2014-02-24 14:57
It seems a problem in the script. I will do a quick fix.

**Comment by cubieplayer** [comment] 2014-02-24 15:48
Hi, Thanks for reporting the problem. It has been fixed now. try apt-get update and upgrade again.

**Closed as completed by cubieplayer** 2014-02-24 15:48 UTC
Labels: Accepted, Sloved, High Priority

**Comment by fieldOfView** [comment] 2014-02-24 16:12
Works for me. Thanks!
